"""ajout_id_entreprise_a_relance

Revision ID: 3e20ae464041
Revises: 770114eb599f
Create Date: 2026-05-06 15:54:39.798709

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e20ae464041"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "770114eb599f"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("relance", sa.Column("id_entreprise", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_relance_id_entreprise"), "relance", ["id_entreprise"], unique=False
    )
    op.create_foreign_key(None, "relance", "entreprise", ["id_entreprise"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "relance", type_="foreignkey")
    op.drop_index(op.f("ix_relance_id_entreprise"), table_name="relance")
    op.drop_column("relance", "id_entreprise")
    # ### end Alembic commands ###
