"""ajout_catalogue_et_maj_tva

Revision ID: 4bdfa2369253
Revises: 5cb758852b35
Create Date: 2026-05-05 22:41:08.489879

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bdfa2369253"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "5cb758852b35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('catalogue_produits',
    #   sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True))
    # op.create_index(op.f('ix_catalogue_produits_id_abonnement'),
    #   'catalogue_produits', ['id_abonnement'], unique=False)
    # op.create_index(op.f('ix_catalogue_produits_reference'),
    #   'catalogue_produits', ['reference'], unique=False)
    op.add_column(
        "taux_tva",
        sa.Column(
            "code_comptable", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    op.create_unique_constraint(None, "taux_tva", ["taux"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "taux_tva", type_="unique")
    op.drop_column("taux_tva", "code_comptable")
    op.drop_index(
        op.f("ix_catalogue_produits_reference"), table_name="catalogue_produits"
    )
    op.drop_index(
        op.f("ix_catalogue_produits_id_abonnement"), table_name="catalogue_produits"
    )
    op.drop_column("catalogue_produits", "date_modification")
    # ### end Alembic commands ###
