"""refactor_utilisateur_role_pour_tenant

Revision ID: 9bc9e40064a6
Revises: 3e20ae464041
Create Date: 2026-05-06 20:55:27.920819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bc9e40064a6"
down_revision: str | Sequence[str] | None = "3e20ae464041"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "utilisateur_role", sa.Column("id_entreprise", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_utilisateur_role_id_entreprise"),
        "utilisateur_role",
        ["id_entreprise"],
        unique=False,
    )
    op.create_index(
        op.f("ix_utilisateur_role_id_role"),
        "utilisateur_role",
        ["id_role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_utilisateur_role_id_utilisateur"),
        "utilisateur_role",
        ["id_utilisateur"],
        unique=False,
    )
    op.create_foreign_key(
        None, "utilisateur_role", "entreprise", ["id_entreprise"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "utilisateur_role", type_="foreignkey")
    op.drop_index(
        op.f("ix_utilisateur_role_id_utilisateur"), table_name="utilisateur_role"
    )
    op.drop_index(op.f("ix_utilisateur_role_id_role"), table_name="utilisateur_role")
    op.drop_index(
        op.f("ix_utilisateur_role_id_entreprise"), table_name="utilisateur_role"
    )
    op.drop_column("utilisateur_role", "id_entreprise")
    # ### end Alembic commands ###
