"""ajout admin_plateforme et compte_protege sur utilisateur

Revision ID: c40f5ade005f
Revises: eb848f5a63ad
Create Date: 2026-07-02 16:42:42.145750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c40f5ade005f"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "eb848f5a63ad"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "utilisateur",
        sa.Column(
            "admin_plateforme", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "utilisateur",
        sa.Column(
            "compte_protege", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.create_index(
        op.f("ix_utilisateur_admin_plateforme"),
        "utilisateur",
        ["admin_plateforme"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_utilisateur_admin_plateforme"), table_name="utilisateur")
    op.drop_column("utilisateur", "compte_protege")
    op.drop_column("utilisateur", "admin_plateforme")
    # ### end Alembic commands ###
