"""ajout nom_original document et suppression table avoir

Revision ID: ccff707cdb81
Revises: 9bc9e40064a6
Create Date: 2026-06-03 17:51:49.015531

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ccff707cdb81"
down_revision: str | Sequence[str] | None = "9bc9e40064a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_avoir_id_entreprise'), table_name='avoir')
    # op.drop_index(op.f('numero_avoir'), table_name='avoir')
    op.drop_table("avoir")
    op.add_column(
        "document",
        sa.Column(
            "nom_original", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "nom_original")
    op.create_table(
        "avoir",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "id_facture_origine", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id_entreprise", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id_createur", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("numero_avoir", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("date_emission", sa.DATE(), nullable=False),
        sa.Column("motif", mysql.TEXT(), nullable=True),
        sa.Column("total_ht", mysql.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("total_tva", mysql.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("total_ttc", mysql.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("date_creation", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_createur"], ["utilisateur.id"], name=op.f("avoir_ibfk_1")
        ),
        sa.ForeignKeyConstraint(
            ["id_entreprise"], ["entreprise.id"], name=op.f("avoir_ibfk_2")
        ),
        sa.ForeignKeyConstraint(
            ["id_facture_origine"], ["facture.id"], name=op.f("avoir_ibfk_3")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("numero_avoir"), "avoir", ["numero_avoir"], unique=True)
    op.create_index(
        op.f("ix_avoir_id_entreprise"), "avoir", ["id_entreprise"], unique=False
    )
    # ### end Alembic commands ###
