"""rend adresse, code_postal, ville optionnels sur utilisateur

Revision ID: eb848f5a63ad
Revises: c3e8b1a9f7d2
Create Date: 2026-07-01 23:09:40.186729

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "eb848f5a63ad"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "c3e8b1a9f7d2"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "utilisateur", "adresse", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "utilisateur",
        "code_postal",
        existing_type=mysql.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "utilisateur", "ville", existing_type=mysql.VARCHAR(length=150), nullable=True
    )
    op.drop_constraint(
        op.f("utilisateur_entreprise_ibfk_2"),
        "utilisateur_entreprise",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "utilisateur_entreprise",
        "utilisateur",
        ["id_utilisateur"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("utilisateur_role_ibfk_2"), "utilisateur_role", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "utilisateur_role",
        "utilisateur",
        ["id_utilisateur"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "utilisateur_role", type_="foreignkey")
    op.create_foreign_key(
        op.f("utilisateur_role_ibfk_2"),
        "utilisateur_role",
        "utilisateur",
        ["id_utilisateur"],
        ["id"],
    )
    op.drop_constraint(None, "utilisateur_entreprise", type_="foreignkey")
    op.create_foreign_key(
        op.f("utilisateur_entreprise_ibfk_2"),
        "utilisateur_entreprise",
        "utilisateur",
        ["id_utilisateur"],
        ["id"],
    )
    op.alter_column(
        "utilisateur", "ville", existing_type=mysql.VARCHAR(length=150), nullable=False
    )
    op.alter_column(
        "utilisateur",
        "code_postal",
        existing_type=mysql.VARCHAR(length=10),
        nullable=False,
    )
    op.alter_column(
        "utilisateur",
        "adresse",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
