"""Initial migration

Revision ID: fa2f9c52e921
Revises:
Create Date: 2026-04-14 20:24:46.539098

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa2f9c52e921"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abonnement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("tarif", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("nombre_max_utilisateurs", sa.Integer(), nullable=False),
        sa.Column("nombre_max_factures_mois", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_abonnement_libelle"), "abonnement", ["libelle"], unique=True
    )
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permission_libelle"), "permission", ["libelle"], unique=True
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_libelle"), "role", ["libelle"], unique=True)
    op.create_table(
        "statut_declaration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("libelle"),
    )
    op.create_table(
        "statut_facture",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("libelle"),
    )
    op.create_table(
        "taux_tva",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("taux", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("est_actif", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "type_notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("est_actif", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("libelle"),
    )
    op.create_table(
        "ville",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "code_postal", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "commune", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False
        ),
        sa.Column(
            "code_insee", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ville_code_postal"), "ville", ["code_postal"], unique=False
    )
    op.create_table(
        "declaration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("periode_debut", sa.Date(), nullable=False),
        sa.Column("periode_fin", sa.Date(), nullable=False),
        sa.Column("montant_ht", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("montant_tva", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("montant_ttc", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id_statut_declaration", sa.Integer(), nullable=False),
        sa.Column(
            "reference_envoi",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("date_envoi", sa.DateTime(), nullable=True),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_statut_declaration"],
            ["statut_declaration.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modele_relance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column(
            "libelle", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("delai_jours", sa.Integer(), nullable=False),
        sa.Column(
            "type_relance",
            sa.Enum("AUTOMATIQUE", "MANUELLE", name="typerelance"),
            nullable=False,
        ),
        sa.Column("contenu_message", sa.Text(), nullable=True),
        sa.Column(
            "canal",
            sa.Enum("DANS_APP", "COURRIEL", name="canalnotification"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permission_role",
        sa.Column("id_role", sa.Integer(), nullable=False),
        sa.Column("id_permission", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_permission"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_role"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id_role", "id_permission"),
    )
    op.create_table(
        "utilisateur",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nom", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "prenom", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "adresse", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "adresse_complement",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("code_postal_id", sa.Integer(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "telephone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "hash_mot_de_passe",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.Column("date_modification", sa.DateTime(), nullable=False),
        sa.Column("date_derniere_connexion", sa.DateTime(), nullable=True),
        sa.Column("est_actif", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_postal_id"],
            ["ville.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_utilisateur_email"), "utilisateur", ["email"], unique=True)
    op.create_table(
        "catalogue_produits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column("id_taux_tva", sa.Integer(), nullable=False),
        sa.Column(
            "type_produit",
            sa.Enum("ARTICLE", "PRESTATION", name="typeproduits"),
            nullable=False,
        ),
        sa.Column(
            "reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "designation", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "prix_unitaire_ht", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("unite", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("est_actif", sa.Boolean(), nullable=False),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_taux_tva"],
            ["taux_tva.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("id_createur", sa.Integer(), nullable=False),
        sa.Column("id_modificateur", sa.Integer(), nullable=True),
        sa.Column(
            "raison_sociale",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("siret", sqlmodel.sql.sqltypes.AutoString(length=14), nullable=True),
        sa.Column(
            "numero_tva", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "adresse", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "adresse_complement",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("id_ville", sa.Integer(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "telephone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column("est_actif", sa.Boolean(), nullable=False),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.Column("date_modification", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_desactivation", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_createur"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_modificateur"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_ville"],
            ["ville.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_tva"),
    )
    op.create_index(op.f("ix_client_email"), "client", ["email"], unique=False)
    op.create_index(
        op.f("ix_client_raison_sociale"), "client", ["raison_sociale"], unique=False
    )
    op.create_index(op.f("ix_client_siret"), "client", ["siret"], unique=True)
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column(
            "nom_fichier", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("date_chargement", sa.DateTime(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum("EN_ATTENTE", "TRAITE", "ERREUR", name="statutdocument"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journal_audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=True),
        sa.Column(
            "entite", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("id_entite", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("CREATION", "MODIFICATION", "SUPPRESSION", name="auditaction"),
            nullable=False,
        ),
        sa.Column("anciennes_valeurs", sa.JSON(), nullable=True),
        sa.Column("nouvelles_valeurs", sa.JSON(), nullable=True),
        sa.Column(
            "adresse_ip", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True
        ),
        sa.Column("date_action", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column("id_type", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "canal",
            sa.Enum("DANS_APP", "COURRIEL", name="canalnotification"),
            nullable=False,
        ),
        sa.Column("est_lu", sa.Boolean(), nullable=False),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.Column("date_lecture", sa.DateTime(), nullable=True),
        sa.Column(
            "lien_action", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("date_expiration", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_type"],
            ["type_notification.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "utilisateur_abonnement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column("est_admin_abonnement", sa.Boolean(), nullable=False),
        sa.Column("date_debut", sa.Date(), nullable=False),
        sa.Column("date_fin", sa.Date(), nullable=True),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum("ACTIF", "EXPIRE", "SUSPENDU", "ANNULE", name="statutsouscription"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_abonnement", "id_utilisateur", name="unique_abonnement_utilisateur"
        ),
    )
    op.create_table(
        "utilisateur_role",
        sa.Column("id_utilisateur", sa.Integer(), nullable=False),
        sa.Column("id_role", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_role"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id_utilisateur", "id_role"),
    )
    op.create_table(
        "facture",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("id_createur", sa.Integer(), nullable=False),
        sa.Column("id_client", sa.Integer(), nullable=True),
        sa.Column("id_document", sa.Integer(), nullable=True),
        sa.Column(
            "numero_facture",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("date_emission", sa.Date(), nullable=False),
        sa.Column("date_echeance", sa.Date(), nullable=True),
        sa.Column("devise", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column(
            "type_facture",
            sa.Enum("FACTURE", "AVOIR", name="typefacture"),
            nullable=False,
        ),
        sa.Column("id_statut", sa.Integer(), nullable=False),
        sa.Column(
            "siret_emetteur", sqlmodel.sql.sqltypes.AutoString(length=14), nullable=True
        ),
        sa.Column(
            "siret_destinataire",
            sqlmodel.sql.sqltypes.AutoString(length=14),
            nullable=True,
        ),
        sa.Column("snapshot_client", sa.JSON(), nullable=True),
        sa.Column("total_ht", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_tva", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_ttc", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "mode_paiement", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("iban", sqlmodel.sql.sqltypes.AutoString(length=34), nullable=True),
        sa.Column(
            "reference_commande",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.Column("date_modification", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_client"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_createur"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_document"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_statut"],
            ["statut_facture.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_facture_numero_facture"), "facture", ["numero_facture"], unique=True
    )
    op.create_table(
        "avoir",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_facture_origine", sa.Integer(), nullable=False),
        sa.Column("id_abonnement", sa.Integer(), nullable=False),
        sa.Column("id_createur", sa.Integer(), nullable=False),
        sa.Column(
            "numero_avoir", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("date_emission", sa.Date(), nullable=False),
        sa.Column("motif", sa.TEXT(), nullable=True),
        sa.Column("total_ht", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_tva", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_ttc", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_abonnement"],
            ["abonnement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_createur"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_facture_origine"],
            ["facture.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_avoir"),
    )
    op.create_table(
        "evenement_pdp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_facture", sa.Integer(), nullable=False),
        sa.Column("id_statut_avant", sa.Integer(), nullable=True),
        sa.Column("id_statut_apres", sa.Integer(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("date_evenement", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_facture"],
            ["facture.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_statut_apres"],
            ["statut_facture.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_statut_avant"],
            ["statut_facture.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extraction_ocr",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_document", sa.Integer(), nullable=False),
        sa.Column("contenu_brut", sa.JSON(), nullable=True),
        sa.Column("score_confiance", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("date_extraction", sa.DateTime(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum("SUCCES", "ECHEC", name="statutextraction"),
            nullable=False,
        ),
        sa.Column("id_facture", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_document"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_facture"],
            ["facture.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "facture_ligne",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_facture", sa.Integer(), nullable=False),
        sa.Column("ordre", sa.Integer(), nullable=False),
        sa.Column(
            "designation", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("quantite", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("unite", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column(
            "prix_unitaire_ht", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("id_taux_tva", sa.Integer(), nullable=False),
        sa.Column("montant_ht", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("montant_tva", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("montant_ttc", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_facture"],
            ["facture.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_taux_tva"],
            ["taux_tva.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paiement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_facture", sa.Integer(), nullable=False),
        sa.Column("id_createur", sa.Integer(), nullable=False),
        sa.Column("montant", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("date_paiement", sa.Date(), nullable=False),
        sa.Column(
            "mode_paiement", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("date_creation", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_createur"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_facture"],
            ["facture.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_facture", sa.Integer(), nullable=False),
        sa.Column("id_modele_relance", sa.Integer(), nullable=True),
        sa.Column("id_utilisateur", sa.Integer(), nullable=True),
        sa.Column(
            "type_relance",
            sa.Enum("AUTOMATIQUE", "MANUELLE", name="typerelance"),
            nullable=False,
        ),
        sa.Column("date_relance", sa.DateTime(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum("ENVOYEE", "ECHOUEE", name="statutrelance"),
            nullable=False,
        ),
        sa.Column("message_envoye", sa.Text(), nullable=True),
        sa.Column(
            "erreur", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["id_facture"],
            ["facture.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_modele_relance"],
            ["modele_relance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_utilisateur"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relance")
    op.drop_table("paiement")
    op.drop_table("facture_ligne")
    op.drop_table("extraction_ocr")
    op.drop_table("evenement_pdp")
    op.drop_table("avoir")
    op.drop_index(op.f("ix_facture_numero_facture"), table_name="facture")
    op.drop_table("facture")
    op.drop_table("utilisateur_role")
    op.drop_table("utilisateur_abonnement")
    op.drop_table("notification")
    op.drop_table("journal_audit")
    op.drop_table("document")
    op.drop_index(op.f("ix_client_siret"), table_name="client")
    op.drop_index(op.f("ix_client_raison_sociale"), table_name="client")
    op.drop_index(op.f("ix_client_email"), table_name="client")
    op.drop_table("client")
    op.drop_table("catalogue_produits")
    op.drop_index(op.f("ix_utilisateur_email"), table_name="utilisateur")
    op.drop_table("utilisateur")
    op.drop_table("permission_role")
    op.drop_table("modele_relance")
    op.drop_table("declaration")
    op.drop_index(op.f("ix_ville_code_postal"), table_name="ville")
    op.drop_table("ville")
    op.drop_table("type_notification")
    op.drop_table("taux_tva")
    op.drop_table("statut_facture")
    op.drop_table("statut_declaration")
    op.drop_index(op.f("ix_role_libelle"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_permission_libelle"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_abonnement_libelle"), table_name="abonnement")
    op.drop_table("abonnement")
    # ### end Alembic commands ###
